# Generated by Django 5.0 on 2025-10-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_region_alter_item_order_alter_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(choices=[('NA', 'North America'), ('EU', 'Europe'), ('AS', 'Asia'), ('SA', 'South America'), ('AF', 'Africa'), ('OC', 'Oceania')], max_length=2),
        ),
    ]
